### ISSUE TITLE
Error using Python 3.9.2

### ISSUE THREAD

**Issue by Almazick** [HTPC-Manager/HTPC-Manager#21]
### Reporting Issues:
- [ ] Branch
Master 2
- [ ] Operating system
Debian 11
- [ ] Python version
3.9.2

Using the following command to install it
python3 -m venv venv
source venv/bin/activate
cd venv/bin
git  clone https://github.com/HTPC-Manager/HTPC-Manager.git 
cd HTPC-Manager/
pip3 install pip --upgrade
pip3 install --no-cache-dir wheel  colorama xmltodict ssdp mako cherrypy sqlobject requests requests_futures jsonrpclib apscheduler

- [ ] **FULL** log (not just a few lines!) that has the error.
<details><summary>Expand log</summary>

```
Paste your full log here
```
Starting HTPC Manager on port 8085.
Start your browser and go to http://localhost:8085
*******************************************************************
Traceback (most recent call last):
  File "/root/htpc/venv/bin/HTPC-Manager/./Htpc.py", line 268, in <module>
    main()
  File "/root/htpc/venv/bin/HTPC-Manager/./Htpc.py", line 265, in main
    start()
  File "/root/htpc/venv/bin/HTPC-Manager/htpc/server.py", line 195, in start
    cherrypy.config.update({
  File "/root/htpc/venv/lib/python3.9/site-packages/cherrypy/_cpconfig.py", line 157, in update
    super(Config, self).update(config)
  File "/root/htpc/venv/lib/python3.9/site-packages/cherrypy/lib/reprconf.py", line 130, in update
    self._apply(Parser.load(config))
  File "/root/htpc/venv/lib/python3.9/site-packages/cherrypy/_cpconfig.py", line 167, in _apply
    super(Config, self)._apply(config)
  File "/root/htpc/venv/lib/python3.9/site-packages/cherrypy/lib/reprconf.py", line 142, in _apply
    self.namespaces(config)
  File "/root/htpc/venv/lib/python3.9/site-packages/cherrypy/lib/reprconf.py", line 92, in __call__
    handler(k, v)
  File "/root/htpc/venv/lib/python3.9/site-packages/cherrypy/_cpconfig.py", line 270, in _engine_namespace_handler
    plugin = getattr(engine, plugin)
AttributeError: 'Bus' object has no attribute 'timeout_monitor'

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

**Comment by Almazick** [comment]
Compiled Python 3.7.3 and set it up using python3.7 -m venv htpc and got the same error

**Comment by MichaIng** [comment]
Probably the CherryPy version we force starts to cause issues now: https://github.com/HTPC-Manager/HTPC-Manager/blob/master2/requirements.txt#L14

Can you try that before doing the pip install:
```
sed -i '/cherrypy/c\cherrypy' requirements.txt
```
So the newest version is pulled.

@gmiranda I remember you pinned that version because of performance reasons. Probably it can be re-validated.
But probably it's not even the issue here. I see if I find time to test, including #3 to have the newest pySMART added until it is uploaded to PyPI.

**Comment by MichaIng** [comment]
Ah lol, I misread the situation. The issue is not the too low CherryPy version, but the too recent version you manually installed. Please use the `requirements.txt` to install dependencies, which contains `cherrypy < 9.0`, which still has support for `timeout_monitor`, which got removed with v12: https://github.com/cherrypy/cherrypy/blob/main/CHANGES.rst#v1200
```
pip3 install -r requirements.txt
```
It's a good idea to replace this call and re-evaluate whether to stay on such an old CherryPy version or not, but that's a different question. I'll hence mark this issue as closed.
